import fs from 'fs';
import path from 'path';

const DB_PATH = './data/db.json';
if (!fs.existsSync(DB_PATH)) {
  console.error('db.json not found!');
  process.exit(1);
}

const db = JSON.parse(fs.readFileSync(DB_PATH, 'utf-8'));

const cameras = [
  {
    id: 'cam-01',
    name: 'Sturgis Motorcycle Rally Cam',
    location: 'Main St, Sturgis, South Dakota, USA',
    group: 'Public Square / Events',
    ip: '192.168.1.101',
    rtspUrl: 'rtsp://live.webcamera24.com:554/usa/sturgis',
    channel: 1,
    streamPath: '/live/cam-01',
    transport: 'tcp',
    sourceType: 'embed',
    sourceUrl: 'https://webcamera24.com/camera/usa/sturgis-motorcycle-rally/',
    embedUrl: 'https://www.youtube-nocookie.com/embed/uu82CI54eJU?autoplay=1&mute=1&enablejsapi=1',
    thumbnailUrl: 'https://cdn.webcamera24.com/static/image/camera/detail/sturgis-motorcycle-rally-webcamtaxi/thumbnail/968x545/maxresdefault.webp',
    webcam24Url: 'https://webcamera24.com/camera/usa/sturgis-motorcycle-rally/',
    status: 'online',
    enabled: true,
    fps: 30,
    resolution: '1920x1080',
    bitrateKbps: 4096,
    latencyMs: 45,
    capabilities: {
      ptz: true,
      audio: true,
      multiStream: true,
      zoom: true,
      presets: ['Harley Rally Point', 'Main Street West', 'Civic Crossing'],
    },
    streams: {
      high: '1080p @ 30 FPS (4 Mbps)',
      standard: '720p @ 25 FPS (2 Mbps)',
      smooth: '480p @ 15 FPS (800 Kbps)',
    },
    hasAuth: false,
    isDemo: false,
    lastPing: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cam-02',
    name: 'Las Vegas Bridge Street Cam',
    location: 'Bridge St, Las Vegas, New Mexico, USA',
    group: 'Traffic / Downtown',
    ip: '192.168.1.102',
    rtspUrl: 'rtsp://live.webcamera24.com:554/usa/lasvegas',
    channel: 2,
    streamPath: '/live/cam-02',
    transport: 'tcp',
    sourceType: 'embed',
    sourceUrl: 'https://webcamera24.com/camera/usa/lasvegas-bridge-street-cam/',
    embedUrl: 'https://www.youtube-nocookie.com/embed/sw8MuxrKcs8?autoplay=1&mute=1&enablejsapi=1',
    thumbnailUrl: 'https://cdn.webcamera24.com/static/image/camera/detail/lasvegas-bridge-street-cam-webcamtaxi/thumbnail/968x545/usa-new-mexico-las-vegas.webp',
    webcam24Url: 'https://webcamera24.com/camera/usa/lasvegas-bridge-street-cam/',
    status: 'online',
    enabled: true,
    fps: 30,
    resolution: '1920x1080',
    bitrateKbps: 4096,
    latencyMs: 52,
    capabilities: {
      ptz: true,
      audio: true,
      multiStream: true,
      zoom: true,
      presets: ['Bridge St Plaza', 'Historic District', 'West Intersection'],
    },
    streams: {
      high: '1080p @ 30 FPS',
      standard: '720p @ 25 FPS',
      smooth: '480p @ 15 FPS',
    },
    hasAuth: false,
    isDemo: false,
    lastPing: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cam-03',
    name: 'Bandai Bridge Niigata Cam',
    location: 'Shinano River, Niigata, Japan',
    group: 'Infrastructure / Bridge',
    ip: '192.168.1.103',
    rtspUrl: 'rtsp://live.webcamera24.com:554/japan/bandai',
    channel: 3,
    streamPath: '/live/cam-03',
    transport: 'tcp',
    sourceType: 'embed',
    sourceUrl: 'https://webcamera24.com/camera/japan/bandai-bridge-cam/',
    embedUrl: 'https://www.youtube-nocookie.com/embed/s_jLXm299n4?autoplay=1&mute=1&enablejsapi=1',
    thumbnailUrl: 'https://cdn.webcamera24.com/static/image/camera/detail/bandai-bridge-cam-webcamtaxi/thumbnail/968x545/japan-niigata-bandai-bridge.webp',
    webcam24Url: 'https://webcamera24.com/camera/japan/bandai-bridge-cam/',
    status: 'online',
    enabled: true,
    fps: 30,
    resolution: '1920x1080',
    bitrateKbps: 4096,
    latencyMs: 88,
    capabilities: {
      ptz: true,
      audio: false,
      multiStream: true,
      zoom: true,
      presets: ['Shinano Riverbank', 'Bandai Arch Span', 'Niigata City Line'],
    },
    streams: {
      high: '1080p @ 30 FPS',
      standard: '720p @ 25 FPS',
      smooth: '480p @ 15 FPS',
    },
    hasAuth: false,
    isDemo: false,
    lastPing: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cam-04',
    name: 'Nantucket Lower Main Street Cam',
    location: 'Cobblestone Historic Area, Nantucket, MA, USA',
    group: 'Commercial / Historic',
    ip: '192.168.1.104',
    rtspUrl: 'rtsp://live.webcamera24.com:554/usa/nantucket',
    channel: 4,
    streamPath: '/live/cam-04',
    transport: 'tcp',
    sourceType: 'embed',
    sourceUrl: 'https://webcamera24.com/camera/usa/nantucket-lower-main-street-cam/',
    embedUrl: 'https://www.youtube-nocookie.com/embed/sp-FHZY95QM?autoplay=1&mute=1&enablejsapi=1',
    thumbnailUrl: 'https://cdn.webcamera24.com/static/image/camera/detail/nantucket-lower-main-street-cam-webcamtaxi/thumbnail/968x545/england-devon-exmouth-marina.webp',
    webcam24Url: 'https://webcamera24.com/camera/usa/nantucket-lower-main-street-cam/',
    status: 'online',
    enabled: true,
    fps: 30,
    resolution: '1920x1080',
    bitrateKbps: 3500,
    latencyMs: 42,
    capabilities: {
      ptz: false,
      audio: true,
      multiStream: true,
      zoom: true,
    },
    streams: {
      high: '1080p @ 30 FPS',
      standard: '720p @ 25 FPS',
      smooth: '480p @ 15 FPS',
    },
    hasAuth: false,
    isDemo: false,
    lastPing: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cam-05',
    name: 'Philadelphia Triangle Square Cam',
    location: 'Kensington Triangle, Philadelphia, PA, USA',
    group: 'Urban / Junction',
    ip: '192.168.1.105',
    rtspUrl: 'rtsp://live.webcamera24.com:554/usa/philly',
    channel: 5,
    streamPath: '/live/cam-05',
    transport: 'tcp',
    sourceType: 'embed',
    sourceUrl: 'https://webcamera24.com/camera/usa/philadelphia-triangle-square-cam/',
    embedUrl: 'https://www.youtube-nocookie.com/embed/jAZjvlaBW3Y?autoplay=1&mute=1&enablejsapi=1',
    thumbnailUrl: 'https://cdn.webcamera24.com/static/image/camera/detail/philadelphia-triangle-square-cam-webcamtaxi/thumbnail/968x545/usa-kensington-philadelphia-triangle-square.webp',
    webcam24Url: 'https://webcamera24.com/camera/usa/philadelphia-triangle-square-cam/',
    status: 'online',
    enabled: true,
    fps: 30,
    resolution: '1920x1080',
    bitrateKbps: 4096,
    latencyMs: 35,
    capabilities: {
      ptz: true,
      audio: true,
      multiStream: true,
      zoom: true,
      presets: ['Triangle Square', 'Frankford Ave Transit', 'Pedestrian Walkway'],
    },
    streams: {
      high: '1080p @ 30 FPS',
      standard: '720p @ 25 FPS',
      smooth: '480p @ 15 FPS',
    },
    hasAuth: false,
    isDemo: false,
    lastPing: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cam-06',
    name: 'Auto Service Vilgud Klin Workshop Cam',
    location: 'Volokolamskoe Hwy 22, Klin, Moscow Oblast, Russia',
    group: 'Logistics / Workshop',
    ip: '192.168.1.106',
    rtspUrl: 'rtsp://live.webcamera24.com:554/russia/klin',
    channel: 6,
    streamPath: '/live/cam-06',
    transport: 'tcp',
    sourceType: 'embed',
    sourceUrl: 'https://webcamera24.com/camera/russia/4464-klin-ceh/',
    embedUrl: 'https://open.ivideon.com/embed/v2/?server=100-3c8e1f6d6762afad5bd69c63dfeff2a8&camera=0&width=&height=&lang=en',
    thumbnailUrl: 'https://cdn.webcamera24.com/static/image/camera/detail/4464-klin-ceh-uastreaming/thumbnail/968x545/4464_1692113736_rzkxizhhlxfihwisawnlpapojteaxifdomyrsexv.webp',
    webcam24Url: 'https://webcamera24.com/camera/russia/4464-klin-ceh/',
    status: 'online',
    enabled: true,
    fps: 25,
    resolution: '1280x720',
    bitrateKbps: 2048,
    latencyMs: 110,
    capabilities: {
      ptz: false,
      audio: false,
      multiStream: true,
      zoom: true,
    },
    streams: {
      high: '720p @ 25 FPS',
      standard: '480p @ 20 FPS',
      smooth: '360p @ 15 FPS',
    },
    hasAuth: false,
    isDemo: false,
    lastPing: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cam-07',
    name: 'Muscatine Merrill Hotel Railcam',
    location: 'Mississippi Riverfront, Muscatine, Iowa, USA',
    group: 'Rail / Transit',
    ip: '192.168.1.107',
    rtspUrl: 'rtsp://live.webcamera24.com:554/usa/muscatine',
    channel: 7,
    streamPath: '/live/cam-07',
    transport: 'tcp',
    sourceType: 'embed',
    sourceUrl: 'https://webcamera24.com/camera/usa/muscatine-merrill-hotel-railcam/',
    embedUrl: 'https://www.youtube-nocookie.com/embed/jld8d8xgMbc?autoplay=1&mute=1&enablejsapi=1',
    thumbnailUrl: 'https://cdn.webcamera24.com/static/image/camera/detail/muscatine-merrill-hotel-railcam-webcamtaxi/thumbnail/968x545/maxresdefault.webp',
    webcam24Url: 'https://webcamera24.com/camera/usa/muscatine-merrill-hotel-railcam/',
    status: 'online',
    enabled: true,
    fps: 30,
    resolution: '1920x1080',
    bitrateKbps: 4096,
    latencyMs: 48,
    capabilities: {
      ptz: true,
      audio: true,
      multiStream: true,
      zoom: true,
      presets: ['CPKC Mainline Track', 'Mississippi River View', 'Harbor Marina'],
    },
    streams: {
      high: '1080p @ 30 FPS',
      standard: '720p @ 25 FPS',
      smooth: '480p @ 15 FPS',
    },
    hasAuth: false,
    isDemo: false,
    lastPing: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cam-08',
    name: 'Ritz Madeira Avenida Arriaga Cam',
    location: 'Avenida Arriaga, Funchal, Madeira, Portugal',
    group: 'Promenade / European Plaza',
    ip: '192.168.1.108',
    rtspUrl: 'rtsp://live.webcamera24.com:554/portugal/ritz',
    channel: 8,
    streamPath: '/live/cam-08',
    transport: 'tcp',
    sourceType: 'embed',
    sourceUrl: 'https://webcamera24.com/camera/portugal/ritz-livecam/',
    embedUrl: 'https://www.youtube-nocookie.com/embed/afyrMxe0qjg?autoplay=1&mute=1&enablejsapi=1',
    thumbnailUrl: 'https://cdn.webcamera24.com/static/image/camera/detail/ritz-livecam-webcamtaxi/thumbnail/968x545/maxresdefault.webp',
    webcam24Url: 'https://webcamera24.com/camera/portugal/ritz-livecam/',
    status: 'online',
    enabled: true,
    fps: 30,
    resolution: '1920x1080',
    bitrateKbps: 4096,
    latencyMs: 76,
    capabilities: {
      ptz: true,
      audio: true,
      multiStream: true,
      zoom: true,
      presets: ['Avenida Promenade', 'Municipal Garden', 'Cafe Patio'],
    },
    streams: {
      high: '1080p @ 30 FPS',
      standard: '720p @ 25 FPS',
      smooth: '480p @ 15 FPS',
    },
    hasAuth: false,
    isDemo: false,
    lastPing: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cam-09',
    name: 'Fort Lauderdale Beach Bar Cam',
    location: 'Beach Blvd, Fort Lauderdale, Florida, USA',
    group: 'Hospitality / Interior',
    ip: '192.168.1.109',
    rtspUrl: 'rtsp://live.webcamera24.com:554/usa/ftlauderdale',
    channel: 9,
    streamPath: '/live/cam-09',
    transport: 'tcp',
    sourceType: 'embed',
    sourceUrl: 'https://webcamera24.com/camera/usa/fort-lauderdale-beach-bar-interior/',
    embedUrl: 'https://www.youtube-nocookie.com/embed/wVNt3l657X0?autoplay=1&mute=1&enablejsapi=1',
    thumbnailUrl: 'https://cdn.webcamera24.com/static/image/camera/detail/fort-lauderdale-beach-bar-interior-youtube/thumbnail/968x545/fort-lauderdale-beach-bar-interior.webp',
    webcam24Url: 'https://webcamera24.com/camera/usa/fort-lauderdale-beach-bar-interior/',
    status: 'online',
    enabled: true,
    fps: 30,
    resolution: '1920x1080',
    bitrateKbps: 3800,
    latencyMs: 55,
    capabilities: {
      ptz: false,
      audio: true,
      multiStream: true,
      zoom: true,
    },
    streams: {
      high: '1080p @ 30 FPS',
      standard: '720p @ 25 FPS',
      smooth: '480p @ 15 FPS',
    },
    hasAuth: false,
    isDemo: false,
    lastPing: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cam-10',
    name: 'Sydney Harbour Panoramic Cam',
    location: 'Sydney Harbour, New South Wales, Australia',
    group: 'Maritime / Port',
    ip: '192.168.1.110',
    rtspUrl: 'rtsp://live.webcamera24.com:554/australia/sydney',
    channel: 10,
    streamPath: '/live/cam-10',
    transport: 'tcp',
    sourceType: 'embed',
    sourceUrl: 'https://webcamera24.com/camera/australia/sydney-harbour-cam/',
    embedUrl: 'https://www.youtube-nocookie.com/embed/5uZa3-RMFos?autoplay=1&mute=1&enablejsapi=1',
    thumbnailUrl: 'https://cdn.webcamera24.com/static/image/camera/detail/sydney-harbour-cam-webcamtaxi/thumbnail/968x545/australia-new-south-wales-sydney-harbour.webp',
    webcam24Url: 'https://webcamera24.com/camera/australia/sydney-harbour-cam/',
    status: 'online',
    enabled: true,
    fps: 30,
    resolution: '1920x1080',
    bitrateKbps: 4096,
    latencyMs: 125,
    capabilities: {
      ptz: true,
      audio: false,
      multiStream: true,
      zoom: true,
      presets: ['Sydney Opera House', 'Harbour Bridge', 'Ferry Terminal'],
    },
    streams: {
      high: '1080p @ 30 FPS',
      standard: '720p @ 25 FPS',
      smooth: '480p @ 15 FPS',
    },
    hasAuth: false,
    isDemo: false,
    lastPing: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cam-11',
    name: 'Shantikunj Gayatri Pariwar Haridwar Cam',
    location: 'Ganga Riverbank, Haridwar, Uttarakhand, India',
    group: 'Cultural / Campus',
    ip: '192.168.1.111',
    rtspUrl: 'rtsp://live.webcamera24.com:554/india/haridwar',
    channel: 11,
    streamPath: '/live/cam-11',
    transport: 'tcp',
    sourceType: 'embed',
    sourceUrl: 'https://webcamera24.com/camera/india/shantikunj-gayatri-pariwar-haridwar/',
    embedUrl: 'https://www.youtube-nocookie.com/embed/Bi9cRN61nOY?autoplay=1&mute=1&enablejsapi=1',
    thumbnailUrl: 'https://cdn.webcamera24.com/static/image/camera/detail/shantikunj-gayatri-pariwar-haridwar-webcamtaxi/thumbnail/968x545/maxresdefault.webp',
    webcam24Url: 'https://webcamera24.com/camera/india/shantikunj-gayatri-pariwar-haridwar/',
    status: 'online',
    enabled: true,
    fps: 30,
    resolution: '1920x1080',
    bitrateKbps: 3500,
    latencyMs: 22,
    capabilities: {
      ptz: true,
      audio: true,
      multiStream: true,
      zoom: true,
      presets: ['Yagya Shala', 'Pragyeshwar Mahakal', 'Campus Gateway'],
    },
    streams: {
      high: '1080p @ 30 FPS',
      standard: '720p @ 25 FPS',
      smooth: '480p @ 15 FPS',
    },
    hasAuth: false,
    isDemo: false,
    lastPing: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cam-12',
    name: 'Elbo Room Bar Beachfront Cam',
    location: 'Las Olas Blvd, Fort Lauderdale, Florida, USA',
    group: 'Commercial / Coastal',
    ip: '192.168.1.112',
    rtspUrl: 'rtsp://live.webcamera24.com:554/usa/elboroom',
    channel: 12,
    streamPath: '/live/cam-12',
    transport: 'tcp',
    sourceType: 'embed',
    sourceUrl: 'https://webcamera24.com/camera/usa/elboroom-bar-band-cam/',
    embedUrl: 'https://www.youtube-nocookie.com/embed/YWs0HMRVCBY?autoplay=1&mute=1&enablejsapi=1',
    thumbnailUrl: 'https://cdn.webcamera24.com/static/image/camera/detail/elboroom-bar-band-cam-webcamtaxi/thumbnail/968x545/usa-florida-elbo-room-bar.webp',
    webcam24Url: 'https://webcamera24.com/camera/usa/elboroom-bar-band-cam/',
    status: 'online',
    enabled: true,
    fps: 30,
    resolution: '1920x1080',
    bitrateKbps: 4096,
    latencyMs: 45,
    capabilities: {
      ptz: true,
      audio: true,
      multiStream: true,
      zoom: true,
      presets: ['Stage View', 'Las Olas Intersection', 'Atlantic Oceanfront'],
    },
    streams: {
      high: '1080p @ 30 FPS',
      standard: '720p @ 25 FPS',
      smooth: '480p @ 15 FPS',
    },
    hasAuth: false,
    isDemo: false,
    lastPing: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cam-13',
    name: 'Avenida Brasil Balneário Camboriú Cam',
    location: 'Avenida Brasil, Balneário Camboriú, Santa Catarina, Brazil',
    group: 'Traffic / Coastal Boulevard',
    ip: '192.168.1.113',
    rtspUrl: 'rtsp://live.webcamera24.com:554/brazil/avenidabrasil',
    channel: 13,
    streamPath: '/live/cam-13',
    transport: 'tcp',
    sourceType: 'embed',
    sourceUrl: 'https://webcamera24.com/camera/brazil/avenida-brasil-livecam/',
    embedUrl: 'https://www.youtube-nocookie.com/embed/ZMcmtGYYg5E?autoplay=1&mute=1&enablejsapi=1',
    thumbnailUrl: 'https://cdn.webcamera24.com/static/image/camera/detail/avenida-brasil-livecam-webcamtaxi/thumbnail/968x545/brazil-santa-catarina-avenida-brasil.webp',
    webcam24Url: 'https://webcamera24.com/camera/brazil/avenida-brasil-livecam/',
    status: 'online',
    enabled: true,
    fps: 30,
    resolution: '1920x1080',
    bitrateKbps: 4096,
    latencyMs: 92,
    capabilities: {
      ptz: true,
      audio: false,
      multiStream: true,
      zoom: true,
      presets: ['Avenida Brasil South', 'Praia Central View', 'City Center'],
    },
    streams: {
      high: '1080p @ 30 FPS',
      standard: '720p @ 25 FPS',
      smooth: '480p @ 15 FPS',
    },
    hasAuth: false,
    isDemo: false,
    lastPing: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cam-14',
    name: 'Times Square Midtown Sky Cam',
    location: 'Times Square & Midtown, New York City, NY, USA',
    group: 'High Density Urban',
    ip: '192.168.1.114',
    rtspUrl: 'rtsp://live.webcamera24.com:554/usa/timessquare',
    channel: 14,
    streamPath: '/live/cam-14',
    transport: 'tcp',
    sourceType: 'embed',
    sourceUrl: 'https://webcamera24.com/camera/usa/times-square-ball/',
    embedUrl: 'https://www.youtube-nocookie.com/embed/VGnFLdQW39A?autoplay=1&mute=1&enablejsapi=1',
    thumbnailUrl: 'https://cdn.webcamera24.com/static/image/camera/detail/times-square-ball-webcamtaxi/thumbnail/968x545/usa-new-york-times-square-ball.webp',
    webcam24Url: 'https://webcamera24.com/camera/usa/times-square-ball/',
    status: 'online',
    enabled: true,
    fps: 30,
    resolution: '1920x1080',
    bitrateKbps: 4500,
    latencyMs: 30,
    capabilities: {
      ptz: true,
      audio: true,
      multiStream: true,
      zoom: true,
      presets: ['Broadway Plaza', 'Duffy Square', '42nd Street Crossing'],
    },
    streams: {
      high: '1080p @ 30 FPS',
      standard: '720p @ 25 FPS',
      smooth: '480p @ 15 FPS',
    },
    hasAuth: false,
    isDemo: false,
    lastPing: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cam-15',
    name: 'Church Street Marketplace Cam',
    location: 'Church St Mall, Burlington, Vermont, USA',
    group: 'Pedestrian Mall / Commercial',
    ip: '192.168.1.115',
    rtspUrl: 'rtsp://live.webcamera24.com:554/usa/burlington',
    channel: 15,
    streamPath: '/live/cam-15',
    transport: 'tcp',
    sourceType: 'embed',
    sourceUrl: 'https://webcamera24.com/camera/usa/church-street-burlington/',
    embedUrl: 'https://www.youtube-nocookie.com/embed/zl1woMXGGmQ?autoplay=1&mute=1&enablejsapi=1',
    thumbnailUrl: 'https://cdn.webcamera24.com/static/image/camera/detail/church-street-burlington-webcamtaxi/thumbnail/968x545/maxresdefault.webp',
    webcam24Url: 'https://webcamera24.com/camera/usa/church-street-burlington/',
    status: 'online',
    enabled: true,
    fps: 30,
    resolution: '1920x1080',
    bitrateKbps: 3800,
    latencyMs: 38,
    capabilities: {
      ptz: true,
      audio: true,
      multiStream: true,
      zoom: true,
      presets: ['City Hall Park', 'Main Pedestrian Strip', 'Bank Street Corner'],
    },
    streams: {
      high: '1080p @ 30 FPS',
      standard: '720p @ 25 FPS',
      smooth: '480p @ 15 FPS',
    },
    hasAuth: false,
    isDemo: false,
    lastPing: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cam-16',
    name: 'Castelldefels Beach Coastline Cam',
    location: 'Passeig Marítim, Castelldefels, Barcelona, Spain',
    group: 'Perimeter / Coastal',
    ip: '192.168.1.116',
    rtspUrl: 'rtsp://live.webcamera24.com:554/spain/castelldefels',
    channel: 16,
    streamPath: '/live/cam-16',
    transport: 'tcp',
    sourceType: 'embed',
    sourceUrl: 'https://webcamera24.com/camera/spain/castelldefels-beach/',
    embedUrl: 'https://www.youtube-nocookie.com/embed/oe5GPi_C7Go?autoplay=1&mute=1&enablejsapi=1',
    thumbnailUrl: 'https://cdn.webcamera24.com/static/image/camera/detail/castelldefels-beach-webcamtaxi/thumbnail/968x545/maxresdefault.webp',
    webcam24Url: 'https://webcamera24.com/camera/spain/castelldefels-beach/',
    status: 'online',
    enabled: true,
    fps: 30,
    resolution: '1920x1080',
    bitrateKbps: 4096,
    latencyMs: 70,
    capabilities: {
      ptz: true,
      audio: false,
      multiStream: true,
      zoom: true,
      presets: ['Promenade Walkway', 'Beachfront Line', 'Marina Horizon'],
    },
    streams: {
      high: '1080p @ 30 FPS',
      standard: '720p @ 25 FPS',
      smooth: '480p @ 15 FPS',
    },
    hasAuth: false,
    isDemo: false,
    lastPing: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
];

db.cameras = cameras;
fs.writeFileSync(DB_PATH, JSON.stringify(db, null, 2), 'utf-8');
console.log('Successfully updated db.json with all 16 cameras!');
